Update cd-flow.yml

diff --git a/.github/workflows/cd-flow.yml b/.github/workflows/cd-flow.yml
--- a/.github/workflows/cd-flow.yml
+++ b/.github/workflows/cd-flow.yml
@@ -91,31 +91,33 @@ jobs:
       - name: Log in to Docker Hub
         uses: docker/login-action@v2
         with:
-            username: ${{ secrets.DOCKER_USERNAME }}
-            password: ${{ secrets.DOCKER_PASSWORD }}
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
 
-      - name: Checkout repository
-        uses: actions/checkout@v4
-
-      - name: Append version to Docker image tag
+      - name: Set Docker image tag
+        id: set_docker_tag
         run: |
-          echo "Setting Docker image tag with next version: ${{ env.next_version }}"
+          if [ -z "${{ env.next_version }}" ]; then
+            echo "Error: next_version is not set or empty"
+            exit 1
+          fi
           echo "docker_tag=${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:${{ env.next_version }}" >> $GITHUB_ENV
+          echo "docker_tag=${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:${{ env.next_version }}"
 
       - name: Download JAR file
         uses: actions/download-artifact@v2
         with:
-            name: gateway-app
-            path: target
+          name: gateway-app
+          path: target
 
       - name: Build and push Docker image
         uses: docker/build-push-action@v2
         with:
-            context: .
-            push: true
-            tags: |
-              ${{ env.docker_tag }}
-              ${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:latest
-            load: false
-            no-cache: false
-            pull: false
+          context: .
+          push: true
+          tags: |
+            ${{ env.docker_tag }}
+            ${{ secrets.DOCKER_USERNAME }}/coreapi-gateway:latest
+          load: false
+          no-cache: false
+          pull: false
